### ISSUE TITLE
Unable to reproduce

### ISSUE THREAD

**Issue by MAkcanca** [banderlog/daugman#2]
Hi!
I followed the example code, didn't alter anything and used the exact same eye.jpg but I'm unable to reproduce the results.
![image](https://user-images.githubusercontent.com/9960579/88202948-3f52d880-cc52-11ea-9fe3-3568d42ca21f.png)
Here is my result.
Using opencv 4.2.0 on a Ubuntu machine.

Am I missing something?
Thanks!

**Comment by banderlog** [comment]
You did all right and found a bug. It appears that I hardcoded the final answer, which is one that needs to be plotted.
So I need to go back in history and find out where I broke the algorithm.
Very stupid error from my side, sorry. I'll write here when I fix it.

**Comment by banderlog** [comment]
Yep, I've found a bug and fixed it (messed tmp variable name). Please pull the latest changes and try again.

**Comment by banderlog** [comment]
Closed due inactivity
